workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      node: latest
      vars:
        SONAR_HOST_URL: https://chvd.eu.ngrok.io
        SONAR_TOKEN: Encrypted(Z0FBQUFBQmhDbHRhWHFBNTR6QTlZYm1COGVzUl9Fak00dXpsNng1STRhcnJFVUhhQjBjS2tmNmpJQjZGWjJkNzlNZjRGVUhLQ2JlNVdKN3lwUnZlRDh4RHRsd0JPWmRoTE1acjc0V1ZVVTczUmlBTFFwc20tSG5Ucmg3aFZBSkdVMllTQUdVMmtwQ2k=)
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: release
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"       
      - name: Build Android app
        script: ./gradlew assembleRelease sonarqube -Dsonar.projectKey=ChrisReferenceProjects_cwa-app-android -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
    artifacts:
      - app/build/outputs/**/**/*.apk
