name: Update default strings on Translation Delivery

# for testing, needs to be refined when the logic works
on: push

jobs:
  update_default_strings:
    runs-on: ubuntu-latest
    steps:
      - name: Determine branch name
        id: calculate-branch-name
        run: |
          env
          echo GITHUB_REF $GITHUB_REF
          BRANCH=${GITHUB_REF#refs/heads/*}
          echo Branch Name $BRANCH
          echo "::set-output name=BRANCH_NAME::$BRANCH"