name: Update default strings on Translation Delivery

# for testing, needs to be refined when the logic works
on: push

jobs:
  update_default_strings:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        id: extract_branch