name: Update default strings on Translation Delivery

# for testing, needs to be refined when the logic works
on: push

jobs:
  update_default_strings:
    runs-on: ubuntu-latest
    steps:
      - name: Determine branch name
        id: calculate-branch-name
        run: |
          env
          echo GITHUB_REF $GITHUB_REF
          BRANCH=${GITHUB_REF#refs/heads/*}
          ACTOR=${GITHUB_ACTOR}
          echo Branch Name $BRANCH
          echo Actor $ACTOR
          echo "::set-output name=BRANCH::$BRANCH"
          echo "::set-output name=ACTOR::$ACTORE"
      - name: Run if it's a translation delivery
        if: ${{ steps.calculate-branch-name.outputs.BRANCH == 'service-tip-git:release/2.1.x' && steps.calculate-branch-name.outputs.ACTOR == 'service-tip-git'}}
        run: echo its a translation branch